# nvfetcher configuration for ZSH plugins
# Run: nvfetcher build
# This generates _sources/generated.nix with updated hashes

[zsh-defer]
src.git = "https://github.com/romkatv/zsh-defer.git"
fetch.git = "https://github.com/romkatv/zsh-defer.git"

[zsh-autopair]
src.git = "https://github.com/hlissner/zsh-autopair.git"
fetch.git = "https://github.com/hlissner/zsh-autopair.git"

[zsh-bd]
src.git = "https://github.com/Tarrasch/zsh-bd.git"
fetch.git = "https://github.com/Tarrasch/zsh-bd.git"

[zsh_codex]
src.git = "https://github.com/tom-doerr/zsh_codex.git"
fetch.git = "https://github.com/tom-doerr/zsh_codex.git"
git.branch = "main"

[zsh-you-should-use]
src.git = "https://github.com/MichaelAquilina/zsh-you-should-use.git"
fetch.git = "https://github.com/MichaelAquilina/zsh-you-should-use.git"
git.tag = "1.7.3"

[zsh-auto-notify]
src.git = "https://github.com/MichaelAquilina/zsh-auto-notify.git"
fetch.git = "https://github.com/MichaelAquilina/zsh-auto-notify.git"
git.branch = "master"
